# Uncomment the next line to define a global platform for your project
# platform :ios, '14.2'

target 'Yogogo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Yogogo

pod 'IQKeyboardManagerSwift'
pod 'Firebase/Firestore'
pod 'FirebaseFirestoreSwift'
pod 'Kingfisher'
pod 'SwiftLint'
pod 'Mapbox-iOS-SDK', '~> 6.3.0'

end
