# Uncomment the next line to define a global platform for your project
# platform :ios, '14.2'

target 'Insdogram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Yogogo
  pod 'SwiftLint'
  pod 'Mapbox-iOS-SDK', '~> 6.3.0'
  pod 'IQKeyboardManagerSwift'
  pod 'YPImagePicker'
  pod 'Kingfisher'
  pod 'lottie-ios'
  pod 'ProgressHUD'
#  pod 'Appirater'

  # Pods for Firebase
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'

end
